---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: sh -lc 'mvn --version'
      register: maven_test_output
    - name: mvn --version
      debug:
        msg: '{{ maven_test_output.stdout }}'
