---
- name: Testing andrewrothstein.maven (configure)
  hosts: all
  vars:
    maven_config:
      profiles:
        - id: profile-id
          active: true
          repos:
            - id: central
              name: repo
              snapshots:
                enabled: false
              url: https://example.com/blah/libs-releases
            - id: snapshots
              name: repo
              snapshots:
                enabled: true
              url: https://example.com/blah/lib-snapshots
          pluginRepos:
            - id: central
              name: repo
              snapshots:
                enabled: false
              url: https://example.com/blah/plugins-releases
            - id: snapshots
              name: repo
              snapshots:
                enabled: true
              url: https://example.com/blah/plugins-snapshots
        - id: some-profile-id
          active: true
          properties:
            foo: bar
            bar: baz
            ding: bat
      toolchains:
        - ty: jdk
          provides:
            version: 1.8
            vendor: sun
          configuration:
            jdkHome: /usr/local/java
      servers:
        - id: server001
          username: my_login
          password: my_password
          privateKey: ${user.home}/.ssh/id_dsa
          passphrase: some_passphrase
          filePermissions: 664
          directoryPermissions: 775
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'mvn --version'
      ansible.builtin.command: sh -lc 'mvn --version'
      changed_when: false
      register: maven_test_output
    - name: Output of 'mvn --version'
      ansible.builtin.debug:
        msg: '{{ maven_test_output.stdout }}'
