---
- name: Testing andrewrothstein.maven installation
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'mvn --version'
      ansible.builtin.command: sh -lc 'mvn --version'
      changed_when: false
      register: maven_test_output
    - name: Output from 'mvn --version'
      ansible.builtin.debug:
        msg: '{{ maven_test_output.stdout }}'
