---
- name: look for maven installation in {{ maven_install_dir }}...
  become: yes
  stat:
    path: '{{ maven_install_dir }}'
  changed_when: false
  register: maven_binary
- when: not maven_binary.stat.exists
  block:
    - name: downloading {{ maven_tgz_url }} to {{ maven_tmp_tgz }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ maven_tgz_url }}'
        dest: '{{ maven_tmp_tgz }}'
        checksum: '{{ maven_checksum }}'
        timeout: '{{ maven_timeout_seconds | default(60) }}'
        mode: 0644
    - name: unarchiving {{ maven_tmp_tgz }} to {{ maven_parent_install_dir }}...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ maven_tmp_tgz }}'
        dest: '{{ maven_parent_install_dir }}'
        creates: '{{ maven_install_dir }}'
  always:
    - name: cleanup {{ maven_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ maven_tmp_tgz }}'
        state: absent
- name: link {{ maven_link_dir }} to {{ maven_install_dir }}...
  become: yes
  become_user: root
  file:
    src: '{{ maven_install_dir }}'
    dest: '{{ maven_link_dir }}'
    state: link

- name: configurating maven...
  become: yes
  become_user: root
  when: maven_config is defined
  with_items:
    - f: settings.xml
    - f: toolchains.xml
    - f: m2.conf
    - f: maven.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d | default(maven_conf_dir) }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
