---
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{maven_tgz_url}}'
    dest: /tmp/{{maven_tgz}}
    mode: 0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    src: /tmp/{{maven_tgz}}
    dest: '{{maven_parent_install_dir}}'
    creates: '{{maven_install_dir}}'

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{maven_install_dir}}'
    dest: '{{maven_link_dir}}'
    state: link

- name : configurate maven...
  become: yes
  become_user: root
  with_items:
    - f: settings.xml
    - f: toolchains.xml
    - f: m2.conf
    - f: maven.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d|default(maven_conf_dir)}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
